// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int64              `json:"id"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Completed   pgtype.Bool        `json:"completed"`
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DueDate     pgtype.Date        `json:"due_date"`
}

type User struct {
	ID        int64              `json:"id"`
	Name      pgtype.Text        `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Password  pgtype.Text        `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
