// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCompletedTodosByUser(ctx context.Context, userID int64) (int64, error)
	CountPendingTodosByUser(ctx context.Context, userID int64) (int64, error)
	CountTodosByUser(ctx context.Context, userID int64) (int64, error)
	// ============================================
	// TODOS
	// ============================================
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	// ============================================
	// USERS
	// ============================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllTodosByUser(ctx context.Context, userID int64) error
	DeleteTodo(ctx context.Context, id int64) error
	DeleteTodoByUser(ctx context.Context, arg DeleteTodoByUserParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetTodoByID(ctx context.Context, id int64) (Todo, error)
	GetTodoByIDAndUserID(ctx context.Context, arg GetTodoByIDAndUserIDParams) (Todo, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListCompletedTodosByUser(ctx context.Context, userID int64) ([]Todo, error)
	ListPendingTodosByUser(ctx context.Context, userID int64) ([]Todo, error)
	ListTodosByDueDate(ctx context.Context, userID int64) ([]Todo, error)
	ListTodosByUser(ctx context.Context, userID int64) ([]Todo, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkTodoCompleted(ctx context.Context, arg MarkTodoCompletedParams) (Todo, error)
	MarkTodoPending(ctx context.Context, arg MarkTodoPendingParams) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpdateTodoByUser(ctx context.Context, arg UpdateTodoByUserParams) (Todo, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
