// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedTodosByUser = `-- name: CountCompletedTodosByUser :one
SELECT COUNT(*)
FROM todos
WHERE user_id = $1
  AND completed = true
`

func (q *Queries) CountCompletedTodosByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedTodosByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingTodosByUser = `-- name: CountPendingTodosByUser :one
SELECT COUNT(*)
FROM todos
WHERE user_id = $1
  AND completed = false
`

func (q *Queries) CountPendingTodosByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingTodosByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosByUser = `-- name: CountTodosByUser :one
SELECT COUNT(*)
FROM todos
WHERE user_id = $1
`

func (q *Queries) CountTodosByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTodosByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :one

INSERT INTO todos (
    title,
    description,
    user_id,
    due_date
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, title, description, completed, user_id, created_at, due_date
`

type CreateTodoParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	UserID      int64       `json:"user_id"`
	DueDate     pgtype.Date `json:"due_date"`
}

// ============================================
// TODOS
// ============================================
func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.DueDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UserID,
		&i.CreatedAt,
		&i.DueDate,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    name,
    email,
    password
) VALUES (
    $1, $2, $3
)
RETURNING id, name, email, password, created_at
`

type CreateUserParams struct {
	Name     pgtype.Text `json:"name"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
}

// ============================================
// USERS
// ============================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllTodosByUser = `-- name: DeleteAllTodosByUser :exec
DELETE FROM todos
WHERE user_id = $1
`

func (q *Queries) DeleteAllTodosByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllTodosByUser, userID)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const deleteTodoByUser = `-- name: DeleteTodoByUser :exec
DELETE FROM todos
WHERE id = $1
  AND user_id = $2
`

type DeleteTodoByUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTodoByUser(ctx context.Context, arg DeleteTodoByUserParams) error {
	_, err := q.db.Exec(ctx, deleteTodoByUser, arg.ID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, title, description, completed, user_id, created_at, due_date
FROM todos
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTodoByID(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UserID,
		&i.CreatedAt,
		&i.DueDate,
	)
	return i, err
}

const getTodoByIDAndUserID = `-- name: GetTodoByIDAndUserID :one
SELECT id, title, description, completed, user_id, created_at, due_date
FROM todos
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetTodoByIDAndUserIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTodoByIDAndUserID(ctx context.Context, arg GetTodoByIDAndUserIDParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByIDAndUserID, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UserID,
		&i.CreatedAt,
		&i.DueDate,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, created_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listCompletedTodosByUser = `-- name: ListCompletedTodosByUser :many
SELECT id, title, description, completed, user_id, created_at, due_date
FROM todos
WHERE user_id = $1
  AND completed = true
ORDER BY created_at DESC
`

func (q *Queries) ListCompletedTodosByUser(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listCompletedTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.UserID,
			&i.CreatedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTodosByUser = `-- name: ListPendingTodosByUser :many
SELECT id, title, description, completed, user_id, created_at, due_date
FROM todos
WHERE user_id = $1
  AND completed = false
ORDER BY created_at DESC
`

func (q *Queries) ListPendingTodosByUser(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listPendingTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.UserID,
			&i.CreatedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByDueDate = `-- name: ListTodosByDueDate :many
SELECT id, title, description, completed, user_id, created_at, due_date
FROM todos
WHERE user_id = $1
ORDER BY due_date ASC NULLS LAST
`

func (q *Queries) ListTodosByDueDate(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByDueDate, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.UserID,
			&i.CreatedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUser = `-- name: ListTodosByUser :many
SELECT id, title, description, completed, user_id, created_at, due_date
FROM todos
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTodosByUser(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.UserID,
			&i.CreatedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password, created_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTodoCompleted = `-- name: MarkTodoCompleted :one
UPDATE todos
SET completed = true
WHERE id = $1
  AND user_id = $2
RETURNING id, title, description, completed, user_id, created_at, due_date
`

type MarkTodoCompletedParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkTodoCompleted(ctx context.Context, arg MarkTodoCompletedParams) (Todo, error) {
	row := q.db.QueryRow(ctx, markTodoCompleted, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UserID,
		&i.CreatedAt,
		&i.DueDate,
	)
	return i, err
}

const markTodoPending = `-- name: MarkTodoPending :one
UPDATE todos
SET completed = false
WHERE id = $1
  AND user_id = $2
RETURNING id, title, description, completed, user_id, created_at, due_date
`

type MarkTodoPendingParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkTodoPending(ctx context.Context, arg MarkTodoPendingParams) (Todo, error) {
	row := q.db.QueryRow(ctx, markTodoPending, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UserID,
		&i.CreatedAt,
		&i.DueDate,
	)
	return i, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET
    title = $2,
    description = $3,
    completed = $4,
    due_date = $5
WHERE id = $1
RETURNING id, title, description, completed, user_id, created_at, due_date
`

type UpdateTodoParams struct {
	ID          int64       `json:"id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Completed   pgtype.Bool `json:"completed"`
	DueDate     pgtype.Date `json:"due_date"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.DueDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UserID,
		&i.CreatedAt,
		&i.DueDate,
	)
	return i, err
}

const updateTodoByUser = `-- name: UpdateTodoByUser :one
UPDATE todos
SET
    title = $3,
    description = $4,
    completed = $5,
    due_date = $6
WHERE id = $1
  AND user_id = $2
RETURNING id, title, description, completed, user_id, created_at, due_date
`

type UpdateTodoByUserParams struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"user_id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Completed   pgtype.Bool `json:"completed"`
	DueDate     pgtype.Date `json:"due_date"`
}

func (q *Queries) UpdateTodoByUser(ctx context.Context, arg UpdateTodoByUserParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodoByUser,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.DueDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.UserID,
		&i.CreatedAt,
		&i.DueDate,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    email = $3,
    password = $4
WHERE id = $1
RETURNING id, name, email, password, created_at
`

type UpdateUserParams struct {
	ID       int64       `json:"id"`
	Name     pgtype.Text `json:"name"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
