// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Todo struct {
	ID          int32          `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Completed   sql.NullBool   `json:"completed"`
	UserID      int32          `json:"user_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	DueDate     sql.NullTime   `json:"due_date"`
}

type User struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
